# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
  ]

  operations = [
    migrations.CreateModel(
      name='Adaccount',
      fields=[
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('accountname', models.CharField(max_length=250)),
      ],
    ),
  ]
