# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='adaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Adaccount'),
        ),
    ]
