# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('dashboard', '0004_auto_20180107_1640'),
  ]

  operations = [
    migrations.AddField(
      model_name='performance',
      name='conv2',
      field=models.IntegerField(blank=True, null=True),
    ),
    migrations.AddField(
      model_name='performance',
      name='conv3',
      field=models.IntegerField(blank=True, null=True),
    ),
  ]
