# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180107_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='cpc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='cpm',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='ctr',
            field=models.FloatField(),
        ),
    ]
